name: Check PR
on:
    pull_request:

jobs:
  main:
    name: Run checks for specification and conformance
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
      - run: pip install bikeshed

      - name: Run bikeshed
        run: bikeshed spec
